# Generated by Django 4.2.6 on 2023-11-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_remove_package_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
