# Generated by Django 4.2.6 on 2023-11-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_package_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="bg_image",
            field=models.ImageField(default="", upload_to="images/package"),
            preserve_default=False,
        ),
    ]
