# Generated by Django 4.2.6 on 2023-11-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_package_bg_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=200)),
                ("is_success", models.BooleanField()),
            ],
        ),
    ]
