# Generated by Django 4.2.6 on 2023-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("facebook", models.CharField(max_length=200, null=True)),
                ("twitter", models.CharField(max_length=200, null=True)),
                ("instagram", models.CharField(max_length=200, null=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("profile_image", models.ImageField(upload_to="images/founder")),
                ("description", models.TextField()),
            ],
        ),
    ]
